require('./basics')
require('./events')
require('./conditionals')
require('./interpolation')
require('./iteration')
require('./cli')
require('./template')
require('./literal')
console.log('All tests passed')
