require('./basics')
require('./events')
require('./conditionals')
require('./interpolation')
require('./iteration')
require('./cli')
require('./function')
require('./literal')
require('./components')
console.log('All tests passed')
